# Generated by Django 2.2.4 on 2020-08-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srm', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolresource',
            name='h10_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h10_11', to='users.School'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='h11_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h11_12', to='users.School'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='h1_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h1_2', to='users.School'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='h2_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h2_3', to='users.School'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='h9_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='h9_10', to='users.School'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='resourceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srm.ResourceType'),
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='users.School'),
        ),
    ]
